server:
  port: 10000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "${FRONTEND_ORIGIN:http://localhost:3000}"
              - "${FRONTEND_IP_ORIGIN:http://127.0.0.1:3000}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: tour-service
          uri: lb://tour-service
          predicates:
            - Path=/tours/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/companies/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
